### PR TITLE
Use static templatetag to remove hardcoded paths

### PR DESCRIPTION
**Pull request by tubaman**
These hardcoded paths cause issues.  For example, if I want to host the
site at a different root path instead of '/', I have to edit these.

I think I branched from the correct branch(`zero`).  If I understand correctly, you are keeping all the base code for all the starter project on `zero`.

### CODE REVIEW

**Comment by jtauber** [comment]
These files are generated so there's no point editing them.

**Comment by ossanna16** [comment]
@jtauber Can this PR be closed?

**Comment by jtauber** [comment]
Yep, I'll close it.

**Comment by ossanna16** [comment]
Thank you @jtauber!

**Comment by tubaman** [comment]
Can we change the way they are generated to use the static template tag?
Can someone point me to the script?

**Comment by jtauber** [comment]
@paltman can you point @tubaman to where _scripts.html and _styles.html get generated?

@tubaman feel free to open a separate issue to track this.

**Comment by paltman** [comment]
https://github.com/pinax/pinax-starter-projects/blob/zero/gulpfile.js#L51

and

https://github.com/pinax/pinax-starter-projects/blob/zero/gulpfile.js#L56

**Comment by tubaman** [comment]
Ok, here's a new PR that uses the static template tag in the handlebars source: https://github.com/pinax/pinax-starter-projects/pull/30

**Pull request closed without merging**
